name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to latest version

    - name: Create config.js
      run: echo "const OPENAI_API_KEY = '${{ secrets.OPENAIAPIKEY }}';" > config.js

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to latest version
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
